// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tULnWhh1kavR4Q4WMa4deMeLKVeTkg8',
    appId: '1:191893163138:web:f0b5dbc5686f34d44f389b',
    messagingSenderId: '191893163138',
    projectId: 'hairsyou-149cc',
    authDomain: 'hairsyou-149cc.firebaseapp.com',
    storageBucket: 'hairsyou-149cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsGto-k-ZjitO7x5c28oRlHOwxZkN8EI',
    appId: '1:191893163138:android:cbc46213a6520d474f389b',
    messagingSenderId: '191893163138',
    projectId: 'hairsyou-149cc',
    storageBucket: 'hairsyou-149cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPUnVSoOqwiDwL7Q4DAcHDQKxb5vVTFw',
    appId: '1:191893163138:ios:683879d7d423673f4f389b',
    messagingSenderId: '191893163138',
    projectId: 'hairsyou-149cc',
    storageBucket: 'hairsyou-149cc.firebasestorage.app',
    iosBundleId: 'com.example.hairsAndYou',
  );

}